matrix:
  - name: markdown
    sources:
      - "**/*.md"
    dictionary:
      wordlists:
        - .github/wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - md
